# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"

  config.vm.network "private_network", ip: "192.168.33.10"

  config.vm.provider "virtualbox" do |vb|
    vb.name = "staticsite.vagrant.vm"
    # Customize the amount of memory on the VM:
    vb.memory = "512"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
    yum install -y httpd

    chmod 775 /var/www/html
    chown -R root:vagrant /var/www/html

    cp /vagrant/index.html /var/www/html

    systemctl enable httpd
    systemctl start httpd
  SHELL
end
